core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('loginApp.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginApp/urls.py
from django.urls import path
from . import views
from core.views import home

app_name = 'loginApp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('index/', home, name='home')
    
]

loginApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, related_name='user_profile')
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)
    facebook_id = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

core/views.py
from django.contrib.auth import login
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.

# home URL
@login_required
def home(request):
    
    context = {}
    template_name = 'loginApp/home.html'

    return render(request, template_name, context)

loginApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


from .models import UserProfile
from core.views import home
# Create your views here.

def register(request):

    registered = False

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        
        user_obj = User(username=username, email=email)
        user_obj.set_password(password)
        user_obj.save()

        return HttpResponseRedirect(reverse('loginApp:login'))

    else:    
        context = {}
        template_name = 'loginApp/register.html'
        return render(request, template_name, context)


def login_user(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse(home))
             
        else:
            return HttpResponse("invalid login information!")

    else:
        context = {}
        template_name = 'loginApp/login.html'
        return render(request, template_name, context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block css_block %} {% endblock %}
    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Authentication App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

templates/loginApp/home.html
{% extends 'base.html' %}
{% block body_block %}
    <br>
    <center><h2>Welcome to the Authentication app!!!</h2></center>
{% endblock %}

templates/loginApp/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap">

		      	<h3 class="text-center mb-4">Login to the App</h3>
				<form method="POST" class="signup-form">
		      		<div class="form-group mb-3">
		      			<input type="text" name="username" class="form-control" placeholder="username">
		      		</div>
                    <div class="form-group mb-3">
                        <input id="password-field" name="password" type="password" class="form-control" placeholder="Password">
                        <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="form-control btn btn-primary submit px-3">Log in</button>
                    </div>
                {% csrf_token %}
	          </form>
	          <p>I'm new here! <a href="{% url 'loginApp:register' %}">Register</a></p>
	        </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/loginApp/register.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Register</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="login-wrap">

		      	<h3 class="text-center mb-4">Register Today!!</h3>
				<form method="POST" class="signup-form">
		      		<div class="form-group mb-3">
		      			<input type="text" name="username" class="form-control" placeholder="username">
		      		</div>
		      		<div class="form-group mb-3">
		      			<input type="text" name="email" class="form-control" placeholder="user@example.com">
		      		</div>
                    <div class="form-group mb-3">
                        <input id="password-field" name="password" type="password" class="form-control" placeholder="Password">
                        <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="form-control btn btn-primary submit px-3">Submit</button>
                    </div>
                {% csrf_token %}
	          </form>
			  <p>I'm already a member! <a href="{% url 'loginApp:login' %}">Login</a></p>
	        </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>